---
- name: S'assurer que le répertoire du site WordPress existe
  ansible.builtin.file:
    path: /home/vagrant/wordpress-site
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copier le fichier docker-compose.yml sur la VM
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/vagrant/wordpress-site/docker-compose.yml
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copier le fichier .env sur la VM depuis le template
  ansible.builtin.template:
    src: .env.j2
    dest: /home/vagrant/wordpress-site/.env
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Lancer docker-compose pour démarrer les services
  ansible.builtin.shell: |
    docker compose up -d --remove-orphans
  args:
    chdir: /home/vagrant/wordpress-site
  become: true

- name: Afficher les conteneurs Docker en cours d'exécution
  ansible.builtin.shell: docker ps
  register: docker_ps_output
  changed_when: false

- name: Debug containers
  ansible.builtin.debug:
    msg: "{{ docker_ps_output.stdout }}"
