- name: Ensure the WordPress site directory exists
  ansible.builtin.file:
    path: "{{ wordpress_dir }}"
    state: directory
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_user }}"
    mode: '0755'

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ wordpress_dir }}/Dockerfile"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_user }}"
    mode: '0644'

- name: Copy entrypoint script
  copy:
    src: docker-entrypoint.sh
    dest: "{{ wordpress_dir }}/docker-entrypoint.sh"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_user }}"
    mode: '0755'

- name: Copy docker-compose.yml to the VM
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: "{{ wordpress_dir }}/docker-compose.yaml"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_user }}"
    mode: '0644'

- name: Copy .env template to the VM
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ wordpress_dir }}/.env"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_user }}"
    mode: '0644'

- name: Launch docker-compose
  ansible.builtin.shell: |
    docker compose up -d --remove-orphans
  args:
    chdir: "{{ wordpress_dir }}"
  become: true
