services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    networks:
      - wp-net
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=admin@${WORDPRESS_DOMAIN}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - wp-net
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: wordpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wp-net
    restart: unless-stopped

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
      - WORDPRESS_USER_PASSWORD=${WORDPRESS_USER_PASSWORD}
      - VIRTUAL_HOST=${WORDPRESS_DOMAIN}
      - VIRTUAL_PORT=80
      - WORDPRESS_CONFIG_EXTRA=
          define('FORCE_SSL_ADMIN', true);
          if (strpos($$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $$_SERVER['HTTPS'] = 'on';
          }
          if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
          }
      - LETSENCRYPT_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${WORDPRESS_DOMAIN}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wp-net
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=${WORDPRESS_DB_USER}
      - PMA_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - VIRTUAL_HOST=phpmyadmin.${WORDPRESS_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=phpmyadmin.${WORDPRESS_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${WORDPRESS_DOMAIN}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wp-net
    restart: unless-stopped

  duckdns-updater:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=cloud1-test
      - TOKEN=${DUCKDUCKDNS_TOKEN}
      - TZ=Europe/Paris
    networks:
      - wp-net
    restart: unless-stopped

networks:
  wp-net:
    driver: bridge
