services:
  # Reverse proxy for WordPress with automatic TLS (Let's Encrypt)
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    networks:
      - wp-net
    restart: unless-stopped

  # Let's Encrypt companion for automatic SSL certificate
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=admin@${WORDPRESS_DOMAIN}
    depends_on:
      - nginx-proxy
    networks:
      - wp-net
    restart: unless-stopped

  # MariaDB for WordPress database
  db:
    image: mariadb:10.5
    container_name: wordpress-db
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - wp-net
    restart: unless-stopped

  # WordPress site container
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - VIRTUAL_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${WORDPRESS_DOMAIN}
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - wp-net
    restart: unless-stopped

  # phpMyAdmin for easy DB access (internal access only)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=${WORDPRESS_DB_USER}
      - PMA_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - wp-net
    restart: unless-stopped

  # DuckDNS IP updater
  duckdns-updater:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=42lh-cloud-1
      - TOKEN=ea3cff07-f2be-4c42-8207-2afffa5da31d # Token https://www.duckdns.org/domains
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - wp-net

networks:
  wp-net:
    driver: bridge

