---
- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key using apt-key as fallback
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  register: apt_key_result
  changed_when: "'OK' in apt_key_result.stdout"

- name: Add Docker repository using traditional method
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ var_system_docker_deb_architecture[ansible_architecture] | default(ansible_architecture) }}] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    filename: docker

- name: Update apt and install docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "alice"
    groups: docker
    append: yes
  become: true